default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wind_turbines_development
  username: wind_turbines
  password: password
  host: localhost

#test:
#  <<: *default
#  database: myapp_test
#  username: myapp_user
#  password: password
#  host: localhost

#production:
#  <<: *default
#  database: myapp_production
#  username: myapp_user
#  password: <%#= ENV['MYAPP_DATABASE_PASSWORD'] %>
#  host: <%#= ENV['DATABASE_HOST'] || 'localhost' %>
